"""delete association and modified contract

Revision ID: c9fd20207bfb
Revises: 28a7205c50b7
Create Date: 2021-11-05 12:55:16.809438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9fd20207bfb'
down_revision = '28a7205c50b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_customer_apartment')
    op.add_column('tbl_contract', sa.Column('apartment_id', sa.Integer(), nullable=True))
    op.add_column('tbl_contract', sa.Column('first_visit', sa.Date(), nullable=True))
    op.add_column('tbl_contract', sa.Column('status', sa.Enum('potential', 'reserved', 'purchased', name='customerapartmentstatusenum'), nullable=False))
    op.add_column('tbl_contract', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('tbl_contract', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('tbl_contract', sa.Column('approved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tbl_contract', sa.Column('signed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key(None, 'tbl_contract', 'tbl_apartment', ['apartment_id'], ['id'])
    op.create_foreign_key(None, 'tbl_contract', 'tbl_user', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_contract', type_='foreignkey')
    op.drop_constraint(None, 'tbl_contract', type_='foreignkey')
    op.drop_column('tbl_contract', 'signed')
    op.drop_column('tbl_contract', 'approved')
    op.drop_column('tbl_contract', 'approved_by')
    op.drop_column('tbl_contract', 'note')
    op.drop_column('tbl_contract', 'status')
    op.drop_column('tbl_contract', 'first_visit')
    op.drop_column('tbl_contract', 'apartment_id')
    op.create_table('tbl_customer_apartment',
    sa.Column('apartment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_visit', sa.DATE(), nullable=True),
    sa.Column('status', mysql.ENUM('potential', 'reserved', 'purchased'), nullable=False),
    sa.Column('customer_price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_of_creation', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_of_update', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('contract_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['tbl_apartment.id'], name='tbl_customer_apartment_ibfk_1'),
    sa.ForeignKeyConstraint(['approved_by'], ['tbl_user.id'], name='tbl_customer_apartment_ibfk_3'),
    sa.ForeignKeyConstraint(['contract_id'], ['tbl_contract.id'], name='tbl_customer_apartment_ibfk_4'),
    sa.ForeignKeyConstraint(['customer_id'], ['tbl_customer.id'], name='tbl_customer_apartment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
